name: Run Jupyter Notebook

on:
  schedule:
    - cron: '0 12 * * *'  # Uruchomienie codziennie o 12:00 UTC
  workflow_dispatch:  # Możliwość ręcznego uruchomienia

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Jeśli Twój branch to "master", zmień na "master"


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install notebook pandas numpy google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client # Dodaj wymagane pakiety

      - name: Run Jupyter Notebook
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          jupyter nbconvert --to notebook --execute Automatic.ipynb --output wynik.ipynb

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add wynik.ipynb
          git commit -m "Automatyczne uruchomienie notebooka"
          git push
