name: Web Scraping Workflow - 2

on:
  schedule:
    - cron: "0 6 * * *"   # 07:00 UTC
    - cron: "0 10 * * *"  # 11:00 UTC
    - cron: "0 15 * * *"  # 16:00 UTC
    - cron: "0 19 * * *"  # 20:00 UTC
  workflow_dispatch:  # Manual trigger

jobs:
  scraping_job:
    runs-on: ubuntu-latest  # Wybieramy system operacyjny, np. Ubuntu

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Sprawdzenie kodu z repozytorium

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Wybór wersji Pythona

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instalacja zależności z requirements.txt

      - name: Run the web scraping script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  # Ustawienie zmiennej środowiskowej z secrets
        run: |
          python scraper.py  # Uruchomienie skryptu
