name: Run Python Script

on:
  schedule:
    - cron: "0 7 * * *"   # 07:00 UTC
    - cron: "0 11 * * *"  # 11:00 UTC
    - cron: "0 16 * * *"  # 16:00 UTC
    - cron: "0 20 * * *"  # 20:00 UTC
  workflow_dispatch:  # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          run: pip install notebook pandas numpy  
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run script
        run: python scraper.py
